### ISSUE TITLE
Can't access the site when offline

### ISSUE THREAD

**Issue by hrmshandy** [cpriego/valet-linux#86]
Hello,

I have a problem, 
when offline I can't access the site, but when I connect it to wifi and then disconnect it, it can.
I use linux ubuntu 16.04.

![image](https://user-images.githubusercontent.com/8230690/28724562-a68a1050-73e4-11e7-8e4f-64fd82cc3c90.png)

**Comment by hrmshandy** [comment]
any update?

**Comment by cpriego** [comment]
Hi @hrmshandy, I have been able to confirm the bug. I discovered it is caused by network-manager not starting dnsmasq until a connection in established. That's why the workaround is to connect a wifi (it works with cable too) and disconnect.

I'm still investigating a solution for this but I have had very little free time.

**Comment by hrmshandy** [comment]
Ok, Thank you @cpriego, I wait for the solution.

for this time it's ok, but I do not always have connections so I need it whithout connecting it first.

**Comment by sinyadal** [comment]
Same issues on Fedora 26.

**Comment by alehtrem** [comment]
@hrmshandy  
As temporary a workaround for me works well in Ubuntu 17.04
manage /etc/hosts file for add your hostname
example:
add yourhostname.dev or yourhostname.app
run in terminal
```
printf "%s\t%s\n" 127.0.0.1 yourhostname.dev | sudo tee -a /etc/hosts > /dev/null
```
remove
```
sudo sed -i".bak" "/yourhostname.dev/d" /etc/hosts
```

**Comment by clevonnoel** [comment]
Any solution to this yet?

**Comment by cpriego** [comment]
@clevonnoel @hrmshandy last weekend I had time to try a set of different possible solutions to this issue. I'm glad to say I found one very promising one that could potentially fix this and other DNS related issues. I'll be testing the solution through the week to make sure it works across the different distros.

**Comment by clevonnoel** [comment]
@cpriego Any immediate workaround in the interim?

**Comment by cpriego** [comment]
@clevonnoel I have the preview version available in the dnsmasq branch. I've tested it enough to make sure it breaks nothing in Ubuntu, Arch and Fedora.

You could help me by using it. I still need to update the tests. Install the version with the following commands. Anyone is welcomed to try it.
```
composer g require "cpriego/valet-linux:dev-dnsmasq"
valet install
```

**Comment by hrmshandy** [comment]
solved, thanks @cpriego

**Comment by alehtrem** [comment]
@cpriego 
This worked!
Thank a lot for helping me out on this one!

**Comment by clevonnoel** [comment]
@cpriego 
Certainly worked!
Thanks

**Comment by alehtrem** [comment]
I have a problem this dev-dnsmasq branch:
Changing domain TLD... in online
terminal: valet domain app
ping all my *.app is ok
I open any internet page in the browser, is not *.app:
example: www.google.be
```
This site can’t be reached
www.google.be’s server DNS address could not be found.
Try:
Checking the proxy, firewall, and DNS configuration
DNS_PROBE_FINISHED_BAD_CONFIG
```
then terminal: sudo /etc/init.d/network-manager restart
this is ok

**Comment by cpriego** [comment]
@alehtrem what's your distro name and version?

**Comment by alehtrem** [comment]
@cpriego 
linux ubuntu 17.04 desktop

**Comment by alehtrem** [comment]
@cpriego  Remove first Valet ?

**Comment by alehtrem** [comment]
@cpriego 
1.
Re-run composer g require "cpriego/valet-linux:dev-dnsmasq"

![screenshot from 2017-08-31 18-09-39](https://user-images.githubusercontent.com/30339292/29934220-a14d1410-8e7a-11e7-835b-9cb124c34e36.png)

2.
Run valet install

![screenshot from 2017-08-31 18-10-40](https://user-images.githubusercontent.com/30339292/29934256-bde6f7b2-8e7a-11e7-89af-5dad9183cea4.png)

3-6.
Reconnect to your network via the NetworkManager applet (as restarting it causes random disconnections in ubuntu)
Run valet domain dev
Test resolution with ping -c 4 alkjsdflakdsjf.dev. Did it work?
Test resolution with ping -c 4 google.be. Did it work?

![screenshot from 2017-08-31 18-13-55](https://user-images.githubusercontent.com/30339292/29934303-e58b7216-8e7a-11e7-83a7-24d66ce25b24.png)

.7-9
Run valet domain app
Test resolution with ping -c 4 woieruqw.app. Did it work?
Test resolution with ping -c 4 google.be. Did it work?

![screenshot from 2017-08-31 18-15-41](https://user-images.githubusercontent.com/30339292/29934515-cbe2caf2-8e7b-11e7-92ea-127b60bfdbf9.png)

10.
Try to browse the web. Does it work?
Is not work

**Comment by cpriego** [comment]
Thanks for the info.

Please share the output of `systemctl status dnsmasq` and `cat /run/NetworkManager/resolv.conf`

**Comment by alehtrem** [comment]
Run valet domain dev:
browse the web is not work

![screenshot from 2017-08-31 19-13-30](https://user-images.githubusercontent.com/30339292/29936117-52d22918-8e81-11e7-92d7-eb188a22380c.png)

browse the web, is works

![screenshot from 2017-08-31 19-16-00](https://user-images.githubusercontent.com/30339292/29936214-a8e9606e-8e81-11e7-9e84-67aa3a6ff743.png)

**Comment by cpriego** [comment]
@alehtrem I faced the same issue in ubuntu 17.04 but is fixed by simply reconnecting through the network manager applet. Is this just a post-install issue that does not occur after a logout or reboot?

**Comment by alehtrem** [comment]
@cpriego 
And after a logout or reboot...

![screenshot from 2017-09-01 01-43-10](https://user-images.githubusercontent.com/30339292/29949921-7ffaa15e-8eb8-11e7-8943-9a87413fd29b.png)

Run valet domain dev

![screenshot from 2017-09-01 01-45-47](https://user-images.githubusercontent.com/30339292/29949950-be000eda-8eb8-11e7-90c3-16a3b4fbb653.png)

reconnecting through the network manager apple

![screenshot from 2017-09-01 01-48-25](https://user-images.githubusercontent.com/30339292/29949981-fd3a96a6-8eb8-11e7-8119-89bfd40c7758.png)

**Comment by alehtrem** [comment]
I'm reverting to 16.04.3 as that release has no issues whatsoever in relation to dns, slow boot and such. Thanks!

**Comment by defaye** [comment]
Can I just say I was having this issue as well. Version `v2.0.23`. It appears that simply running `valet restart` doesn't trigger dnsmasq to restart.

```
$ valet restart
Restarting php7.0-fpm...
Restarting nginx...
Valet services have been restarted.
```

Running `valet domain test` did the trick.

```
Restarting dnsmasq...
Restarting php7.0-fpm...
Restarting nginx...
Your Valet domain has been updated to [test].
```

**Comment by MerrySean** [comment]
Can't connect to project site without wifi connection (airplain mode) Even if I connect then Disconnect It wont work
 
Ubuntu Version : 18.04  (LTS), 
Valet Linux Version : 2.0.24 , 
Browser : Firefox
-> I tried " `valet domain test`" but still doesnt work
